version: '2'
services:
 mongodb:
   image: mongo:3.3   
   expose:                 
     - "27017"
   volumes:
     - db_data:/data/db
   environment:    
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   image: teamcloudyuga/rsvpapp:mooc
   ports:
    - "5000:5000"
   environment:
    MONGODB_HOST: mongodb
    LINK: http://www.sk.co.kr
    TEXT1: SK
    TEXT2: Cloud Meetup!
    LOGO: https://www.sk.co.kr/lib/images/desktop/media/ci_cont02_img01.png
    COMPANY: SK HOLDINGS
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
